/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.Usuario;
import model.Conta;
import data.ContaData;
import data.dbinfofile;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan
 */
public class JFCadastrarConta extends javax.swing.JFrame {

    /**
     * Creates new form JFCadastrarConta
     */
    private Usuario usuario;
    private Conta conta;
    private ContaData DAO;
    private ArrayList<Conta> listaDeContas;
    private dbinfofile file;
    
    public JFCadastrarConta(Usuario usuario, Conta conta) throws Exception {
        this.usuario = usuario;
        this.conta = conta;
        file = new dbinfofile();
        DAO = new ContaData();
        initComponents();

        listaDeContas = new ArrayList<>();

        CarregaComboBoxTodos();
        CarregaTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDados = new javax.swing.JTable();
        jBGerar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jCCContas = new javax.swing.JComboBox<>();
        jBReivindicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cadastro de Conta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 20));

        jtbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Conta", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbDados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 488, 129));

        jBGerar.setText("Gerar Nova Conta");
        jBGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel6.setText("Reivindicar acesso outra Conta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jCCContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCContasActionPerformed(evt);
            }
        });
        getContentPane().add(jCCContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jBReivindicar.setText("Reivindicar");
        jBReivindicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReivindicarActionPerformed(evt);
            }
        });
        getContentPane().add(jBReivindicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDadosMouseClicked

    }//GEN-LAST:event_jtbDadosMouseClicked

    private void jCCContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCCContasActionPerformed

    private void jBReivindicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReivindicarActionPerformed
        //pegar o numero da conta e atribuir na tabela contas_usuario com o cpf do usuario logado
        try {
            String nroconta = (String) jCCContas.getSelectedItem();
            if (DAO.reivindicar(nroconta, usuario)) {
                JOptionPane.showMessageDialog(this, "A Conta foi incluida em sua posse com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
                
                this.jCCContas.removeAllItems();
                CarregaComboBoxTodos();
                CarregaTabela();
                
                
                
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro: " + erro.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBReivindicarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            this.DAO.getConexao().close();
        } catch (SQLException ex) {
            Logger.getLogger(JFCadastrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jBGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerarActionPerformed
        try {
            if (DAO.gerar(usuario)) {
                JOptionPane.showMessageDialog(this, "Uma nova conta foi gerada em seu nome com Sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
               
                this.jCCContas.removeAllItems();
                CarregaComboBoxTodos();
                CarregaTabela();
            
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: "+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadastrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //    new JFCadastrarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGerar;
    private javax.swing.JButton jBReivindicar;
    private javax.swing.JComboBox<String> jCCContas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbDados;
    // End of variables declaration//GEN-END:variables

    private void CarregaComboBoxTodos() throws IOException {
        try {
            jCCContas.addItem("Selecione uma Conta");
               String url = file.url();
               String login = file.login();
               String password = file.password();
            Connection conn;
            
            conn = DriverManager.getConnection(url, login, password);//classse de conexao com banco
            PreparedStatement ps = conn.prepareStatement("select conta from conta where conta not in (SELECT conta from contas_usuario where cpf = ?)");
            ps.setString(1, usuario.getCpf());
            ResultSet rs;
            rs = ps.executeQuery();

            while (rs.next()) {
                jCCContas.addItem(rs.getString("conta"));
            }
            rs.close();
            conn.close();
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Ocorreu erro ao carregar a Combo Box", "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }

    private void CarregaTabela() {
        try {
            listaDeContas = DAO.listar(usuario);
            DefaultTableModel mp = (DefaultTableModel) jtbDados.getModel();
            mp.setNumRows(0);
            for (Conta u : listaDeContas) {
                mp.addRow(new String[]{""+u.getConta(), ""+u.getSaldo()});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }

}
