/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Conexao;
import data.dbinfofile;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Conta;
import model.Usuario;

/**
 *
 * @author juan
 */
public class JFEscolherConta extends javax.swing.JFrame {
Usuario usuario = new Usuario();
Conta conta = new Conta();
private dbinfofile file;
    /**
     * Creates new form JFCadastrarConta
     */
    public JFEscolherConta(Usuario obj) {
        String cpf = obj.getCpf();
        this.usuario = obj;
        file = new dbinfofile();
        initComponents();
        CarregaComboBox(cpf);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jBLogar = new javax.swing.JButton();
        jCContas = new javax.swing.JComboBox<>();
        jBCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setText("Escolher a Conta");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jBLogar.setText("Logar");
        jBLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogarActionPerformed(evt);
            }
        });
        getContentPane().add(jBLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jCContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCContasActionPerformed(evt);
            }
        });
        getContentPane().add(jCContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jBCadastrar.setText("Cadastrar Nova");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogarActionPerformed
       
        String cont = jCContas.getSelectedItem().toString();
        int conta = Integer.parseInt(cont);
        
    try {
        new JFConta(usuario, conta).setVisible(true);
    } catch (Exception ex) {
        Logger.getLogger(JFEscolherConta.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_jBLogarActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
    try {
        new JFCadastrarConta(usuario, conta).setVisible(true);
    } catch (Exception ex) {
        Logger.getLogger(JFEscolherConta.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jCContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEscolherConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEscolherConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEscolherConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEscolherConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           //     new JFEscolherConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBLogar;
    private javax.swing.JComboBox<String> jCContas;
    private javax.swing.JLabel jLTitulo;
    // End of variables declaration//GEN-END:variables

    private void CarregaComboBox(String cpf) {
        try {
            String url = file.url();
            String login = file.login();
            String password = file.password();
            Connection conn;
            conn = DriverManager.getConnection(url, login, password);//classse de conexao com banco
            PreparedStatement ps = conn.prepareStatement("SELECT conta FROM contas_usuario WHERE cpf=?");
            ps.setString(1, cpf);
            
            ResultSet rs;
            rs = ps.executeQuery();
            
            while (rs.next()) {
                jCContas.addItem(rs.getString("conta"));
            }
            rs.close();
            conn.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Ocorreu erro ao carregar a Combo Box", "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }

}
